version: '3'

services: 
  db:
    image: mysql:latest
    container_name: mysqldb
    restart: 'always'
    volumes: 
      - db_volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment: 
    
      MYSQL_ROOT_PASSWORD: a27e24a0b6a44b16
      MYSQL_DATABASE: "burning_glass_ops"
      MYSQL_USER: temp 
      MYSQL_PASSWORD: tEmp12345
    ports: 
      - "127.0.0.1:3307:3306"
    networks: 
      db_net:
        aliases: 
          - bgtdata

  api: 
    build: 
      context: './api'
      dockerfile: Dockerfile
    container_name: api-service
    restart: 'always'
    ports: 
      - "127.0.0.1:5000:5000"
    depends_on:
      - db
    environment: 
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://temp:tEmp12345@bgtdata/burning_glass_ops"
    networks: 
      - db_net
      - frontend
      

  web:
    image:  nginx:latest
    container_name: dashboard
    restart: 'always'
    depends_on: 
      - api
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html  
    ports: 
      - "80:80"
    networks: 
      - frontend
      - default

volumes: 
  db_volume: 

networks: 
  db_net: 
  frontend:

      
